version: '3.8'

services:
  sei-mcp:
    build: .
    image: sei-mcp:latest
    container_name: sei-mcp
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - SEI_RPC_URL=${SEI_RPC_URL:-https://evm-rpc.sei-apis.com}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - "com.sei.service=mcp"
      - "com.sei.version=0.1.0"
      - "com.sei.chain=sei"
